name: "build"

on:
  push:
    paths-ignore:
      - 'CHANGELOG.md'
      - 'LICENSE'
      - 'README.md'
      - 'renovate.json'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3.0.2
      - uses: ozaytsev86/create-env-file@v1
        with:
          ENV_VUE_APP_BE: ${{ secrets.VUE_APP_BE }}
          ENV_VUE_APP_AUTH0_DOMAIN: ${{ secrets.VUE_APP_AUTH0_DOMAIN }}
          ENV_VUE_APP_AUTH0_CLIENT_ID: ${{ secrets.VUE_APP_AUTH0_CLIENT_ID }}
      - name: Run init
        run: |
          npm install
          npm run build
          cd dist
          sed -i 's-"/-"./-g' index.html
      - name: Deploy website to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4.4.0
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: dist # The folder the action should deploy.